// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_dev_configurations.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp7ID72JFY8JJEddBNUqWmJY4m8hQaJuU',
    appId: '1:553924792954:web:e942660921ff0dd04761c3',
    messagingSenderId: '553924792954',
    projectId: 'refugee-care-staging',
    authDomain: 'refugee-care-staging.firebaseapp.com',
    storageBucket: 'refugee-care-staging.firebasestorage.app',
    measurementId: 'G-QG39759C6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQPo7U7EsXpW0pW1dOzyM-rtQe1Dj_LfA',
    appId: '1:553924792954:android:7013136dbfc1eec84761c3',
    messagingSenderId: '553924792954',
    projectId: 'refugee-care-staging',
    storageBucket: 'refugee-care-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy39qm08-7mcpSMAZTIAhHy93dYmNcVDc',
    appId: '1:553924792954:ios:852de5decebb594d4761c3',
    messagingSenderId: '553924792954',
    projectId: 'refugee-care-staging',
    storageBucket: 'refugee-care-staging.firebasestorage.app',
    iosBundleId: 'com.vanzar.refugeeCare.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy39qm08-7mcpSMAZTIAhHy93dYmNcVDc',
    appId: '1:553924792954:ios:7c53aa4f8b38e4bf4761c3',
    messagingSenderId: '553924792954',
    projectId: 'refugee-care-staging',
    storageBucket: 'refugee-care-staging.firebasestorage.app',
    iosBundleId: 'com.example.refugeeCareMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp7ID72JFY8JJEddBNUqWmJY4m8hQaJuU',
    appId: '1:553924792954:web:0feccfe1123032574761c3',
    messagingSenderId: '553924792954',
    projectId: 'refugee-care-staging',
    authDomain: 'refugee-care-staging.firebaseapp.com',
    storageBucket: 'refugee-care-staging.firebasestorage.app',
    measurementId: 'G-F53JDWW79H',
  );
}