// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_prod_configurations.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI7r2fnU5jtPyKcaIKLscqhUsCilT1B6E',
    appId: '1:1016517091354:web:6b758a828da5f774f4f1a3',
    messagingSenderId: '1016517091354',
    projectId: 'refugeecare-9a790',
    authDomain: 'refugeecare-9a790.firebaseapp.com',
    storageBucket: 'refugeecare-9a790.firebasestorage.app',
    measurementId: 'G-28FJ73S620',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFfIIzcHYjjsgAwzKmT2Z4mkiGuw5Jqis',
    appId: '1:1016517091354:android:649f1b2f2b5eda33f4f1a3',
    messagingSenderId: '1016517091354',
    projectId: 'refugeecare-9a790',
    storageBucket: 'refugeecare-9a790.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlTsfzNG9zGLpye12kaMx5B_KWdyroYCk',
    appId: '1:1016517091354:ios:d35a149b5a84e01cf4f1a3',
    messagingSenderId: '1016517091354',
    projectId: 'refugeecare-9a790',
    storageBucket: 'refugeecare-9a790.firebasestorage.app',
    iosBundleId: 'com.vanzar.refugeeCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlTsfzNG9zGLpye12kaMx5B_KWdyroYCk',
    appId: '1:1016517091354:ios:e85aaca4ddb67c8af4f1a3',
    messagingSenderId: '1016517091354',
    projectId: 'refugeecare-9a790',
    storageBucket: 'refugeecare-9a790.firebasestorage.app',
    iosBundleId: 'com.example.refugeeCareMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI7r2fnU5jtPyKcaIKLscqhUsCilT1B6E',
    appId: '1:1016517091354:web:e30dccc19ee3a835f4f1a3',
    messagingSenderId: '1016517091354',
    projectId: 'refugeecare-9a790',
    authDomain: 'refugeecare-9a790.firebaseapp.com',
    storageBucket: 'refugeecare-9a790.firebasestorage.app',
    measurementId: 'G-SM7HKTC46B',
  );
}