import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:refugee_care_mobile/domain/model/cards/community_cart.dart';
import 'package:refugee_care_mobile/feature/cards/community_card.dart';
import 'package:refugee_care_mobile/feature/cards/details/card_details_screen.dart';

List<CommunityCard> communityCards = [
  CommunityCard(
    name: 'John Doe',
    id: '12345',
    cardNumber: '33343',
    title: 'Mr.',
    type: 'Aliance of Chin Refugees',
    dateOfBirth: '1990-01-01',
    gender: 'Male',
    nationality: 'American',
    dateOfIssue: '2020-01-01',
    dateOfExpiry: '2030-01-01',
    passportPhoto: 'path/to/passportPhoto1.jpg',
    frontSidePhoto: 'path/to/frontSidePhoto1.jpg',
    backSidePhoto: 'path/to/backSidePhoto1.jpg',
    uNHCRNumber: 'UN12345',
    studentNumber: 'ST12345',
    isVerified: true,
  ),
  CommunityCard(
    name: 'Jane Smith',
    id: '67890',
    cardNumber: '33343',
    title: 'Ms.',
    type: 'Aliance of Chin Refugees',
    dateOfBirth: '1992-02-02',
    gender: 'Female',
    nationality: 'Canadian',
    dateOfIssue: '2021-02-02',
    dateOfExpiry: '2031-02-02',
    passportPhoto: 'path/to/passportPhoto2.jpg',
    frontSidePhoto: 'path/to/frontSidePhoto2.jpg',
    backSidePhoto: 'path/to/backSidePhoto2.jpg',
    uNHCRNumber: 'UN67890',
    studentNumber: 'ST67890',
    isVerified: false,
  ),
  CommunityCard(
    name: 'Alice Johnson',
    id: '11121',
    title: 'Mrs.',
    cardNumber: '33343',
    type: 'Chin Refugee Committee',
    dateOfBirth: '1985-03-03',
    gender: 'Female',
    nationality: 'British',
    dateOfIssue: '2019-03-03',
    dateOfExpiry: '2029-03-03',
    passportPhoto: 'path/to/passportPhoto3.jpg',
    frontSidePhoto: 'path/to/frontSidePhoto3.jpg',
    backSidePhoto: 'path/to/backSidePhoto3.jpg',
    uNHCRNumber: 'UN11121',
    studentNumber: 'ST11121',
    isVerified: true,
  ),
  CommunityCard(
    name: 'Bob Brown',
    id: '22232',
    cardNumber: '33343',
    title: 'Mr.',
    type: 'Premium',
    dateOfBirth: '1988-04-04',
    gender: 'Male',
    nationality: 'Australian',
    dateOfIssue: '2022-04-04',
    dateOfExpiry: '2032-04-04',
    passportPhoto: 'path/to/passportPhoto4.jpg',
    frontSidePhoto: 'path/to/frontSidePhoto4.jpg',
    backSidePhoto: 'path/to/backSidePhoto4.jpg',
    uNHCRNumber: 'UN22232',
    studentNumber: 'ST22232',
    isVerified: false,
  ),
  CommunityCard(
    name: 'Charlie Davis',
    id: '33343',
    cardNumber: '33343',
    title: 'Dr.',
    type: 'Chin Refugee Committee',
    dateOfBirth: '1995-05-05',
    gender: 'Male',
    nationality: 'Indian',
    dateOfIssue: '2023-05-05',
    dateOfExpiry: '2033-05-05',
    passportPhoto: 'path/to/passportPhoto5.jpg',
    frontSidePhoto: 'path/to/frontSidePhoto5.jpg',
    backSidePhoto: 'path/to/backSidePhoto5.jpg',
    uNHCRNumber: 'UN33343',
    studentNumber: 'ST33343',
    isVerified: true,
  ),
  CommunityCard(
    name: 'Daisy Evans',
    id: '44454',
    title: 'Ms.',
    type: 'Chin Refugee Committee',
    cardNumber: '33343',
    dateOfBirth: '1983-06-06',
    gender: 'Female',
    nationality: 'German',
    dateOfIssue: '2018-06-06',
    dateOfExpiry: '2028-06-06',
    passportPhoto: 'path/to/passportPhoto6.jpg',
    frontSidePhoto: 'path/to/frontSidePhoto6.jpg',
    backSidePhoto: 'path/to/backSidePhoto6.jpg',
    uNHCRNumber: 'UN44454',
    studentNumber: 'ST44454',
    isVerified: false,
  ),
  CommunityCard(
    name: 'Eve Foster',
    id: '55565',
    cardNumber: '33343',
    title: 'Mrs.',
    type: 'Standard',
    dateOfBirth: '1991-07-07',
    gender: 'Female',
    nationality: 'French',
    dateOfIssue: '2024-07-07',
    dateOfExpiry: '2034-07-07',
    passportPhoto: 'path/to/passportPhoto7.jpg',
    frontSidePhoto: 'path/to/frontSidePhoto7.jpg',
    backSidePhoto: 'path/to/backSidePhoto7.jpg',
    uNHCRNumber: 'UN55565',
    studentNumber: 'ST55565',
    isVerified: true,
  ),
  CommunityCard(
    name: 'Frank Green',
    id: '66676',
    title: 'Mr.',
    type: 'Chin Refugee Committee',
    cardNumber: '33343',
    dateOfBirth: '1980-08-08',
    gender: 'Male',
    nationality: 'Chinese',
    dateOfIssue: '2017-08-08',
    dateOfExpiry: '2027-08-08',
    passportPhoto: 'path/to/passportPhoto8.jpg',
    frontSidePhoto: 'path/to/frontSidePhoto8.jpg',
    backSidePhoto: 'path/to/backSidePhoto8.jpg',
    uNHCRNumber: 'UN66676',
    studentNumber: 'ST66676',
    isVerified: false,
  ),
  CommunityCard(
    name: 'Grace Harris',
    id: '77787',
    title: 'Dr.',
    cardNumber: '33343',
    type: 'Standard',
    dateOfBirth: '1997-09-09',
    gender: 'Female',
    nationality: 'Japanese',
    dateOfIssue: '2025-09-09',
    dateOfExpiry: '2035-09-09',
    passportPhoto: 'path/to/passportPhoto9.jpg',
    frontSidePhoto: 'path/to/frontSidePhoto9.jpg',
    backSidePhoto: 'path/to/backSidePhoto9.jpg',
    uNHCRNumber: 'UN77787',
    studentNumber: 'ST77787',
    isVerified: true,
  ),
  CommunityCard(
    cardNumber: '33343',
    name: 'Henry Johnson',
    id: '88898',
    title: 'Mr.',
    type: 'Aliance of Chin Refugees',
    dateOfBirth: '1987-10-10',
    gender: 'Male',
    nationality: 'Brazilian',
    dateOfIssue: '2026-10-10',
    dateOfExpiry: '2036-10-10',
    passportPhoto: 'path/to/passportPhoto10.jpg',
    frontSidePhoto: 'path/to/frontSidePhoto10.jpg',
    backSidePhoto: 'path/to/backSidePhoto10.jpg',
    uNHCRNumber: 'UN88898',
    studentNumber: 'ST88898',
    isVerified: false,
  ),
];

class RefugeeCardList extends StatelessWidget {
  // Sample data for the refugee cards

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemCount: communityCards.length,
      shrinkWrap: false,
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 16),
      itemBuilder: (context, index) {
        final data = communityCards[index];
        return CommunityCardItem(
          card: data,
          onTap: (card) {
            context.push(CardDetailsScreen.routeName, extra: card);
          },
        );
      },
    );
  }
}
