// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI7r2fnU5jtPyKcaIKLscqhUsCilT1B6E',
    appId: '1:1016517091354:web:72ca8c19d181db43f4f1a3',
    messagingSenderId: '1016517091354',
    projectId: 'refugeecare-9a790',
    authDomain: 'refugeecare-9a790.firebaseapp.com',
    storageBucket: 'refugeecare-9a790.appspot.com',
    measurementId: 'G-SEHYB3G2KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFfIIzcHYjjsgAwzKmT2Z4mkiGuw5Jqis',
    appId: '1:1016517091354:android:9c1387745c647e1cf4f1a3',
    messagingSenderId: '1016517091354',
    projectId: 'refugeecare-9a790',
    storageBucket: 'refugeecare-9a790.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlTsfzNG9zGLpye12kaMx5B_KWdyroYCk',
    appId: '1:1016517091354:ios:94fc56da103b3b8af4f1a3',
    messagingSenderId: '1016517091354',
    projectId: 'refugeecare-9a790',
    storageBucket: 'refugeecare-9a790.appspot.com',
    iosBundleId: 'com.example.refugeeCareMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlTsfzNG9zGLpye12kaMx5B_KWdyroYCk',
    appId: '1:1016517091354:ios:94fc56da103b3b8af4f1a3',
    messagingSenderId: '1016517091354',
    projectId: 'refugeecare-9a790',
    storageBucket: 'refugeecare-9a790.appspot.com',
    iosBundleId: 'com.example.refugeeCareMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI7r2fnU5jtPyKcaIKLscqhUsCilT1B6E',
    appId: '1:1016517091354:web:82b202b0e60d4b0cf4f1a3',
    messagingSenderId: '1016517091354',
    projectId: 'refugeecare-9a790',
    authDomain: 'refugeecare-9a790.firebaseapp.com',
    storageBucket: 'refugeecare-9a790.appspot.com',
    measurementId: 'G-272H08S1QM',
  );
}
